PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS Logs;
DROP TABLE IF EXISTS Notes;
DROP TABLE IF EXISTS Sensors;
DROP TABLE IF EXISTS Achievements;
DROP TABLE IF EXISTS Awards;
DROP TABLE IF EXISTS Plants;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Images;

PRAGMA foreign_keys = ON;