CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE NOT NULL,
    DateJoined TIMESTAMP DEFAULT (DATETIME('now')) NOT NULL
);

CREATE TABLE IF NOT EXISTS Plants (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT UNIQUE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID) NOT NULL
);

CREATE TABLE IF NOT EXISTS Notes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Note TEXT NOT NULL,
    Rating INTEGER NOT NULL,
    Timestamp TIMESTAMP DEFAULT (DATETIME('now')) NOT NULL,
    FOREIGN KEY (PlantID) REFERENCES Plants(ID) NOT NULL
)

CREATE TABLE IF NOT EXISTS Achievements (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT UNIQUE NOT NULL,
    FOREIGN KEY (AwardID) REFERENCES Awards(ID) NOT NULL
)

CREATE TABLE IF NOT EXISTS Awards (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Description TEXT UNIQUE NOT NULL
)

CREATE TABLE IF NOT EXISTS Logs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Temperature FLOAT,
    PH FLOAT,
    FOREIGN KEY (PlantID) REFERENCES Plants(ID) NOT NULL
);