/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["logout_api_auth_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/cas/{redirect64}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cas Callback */
        get: operations["cas_callback_api_auth_cas__redirect64__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Session */
        get: operations["retrieve_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh Token */
        get: operations["refresh_token_api_auth_refresh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete User */
        get: operations["delete_user_api_auth_delete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
<<<<<<< HEAD
    "/api/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Sensors */
        get: operations["get_user_sensors_api_sensors_get"];
        put?: never;
        /** Add Sensor */
        post: operations["add_sensor_api_sensors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/{sensor_id}/session": {
=======
    "/api/sensors/sensors/{sensor_id}/session": {
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Sensor */
<<<<<<< HEAD
        post: operations["activate_sensor_api_sensors__sensor_id__session_post"];
        /** Deactivate Sensor */
        delete: operations["deactivate_sensor_api_sensors__sensor_id__session_delete"];
=======
        post: operations["activate_sensor_api_sensors_sensors__sensor_id__session_post"];
        /** Deactivate Sensor */
        delete: operations["deactivate_sensor_api_sensors_sensors__sensor_id__session_delete"];
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
<<<<<<< HEAD
    "/api/sensors/{sensor_id}": {
=======
    "/api/sensors/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Sensor */
        post: operations["add_sensor_api_sensors_sensors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/sensors/{sensor_id}": {
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Del Sensor */
<<<<<<< HEAD
        delete: operations["del_sensor_api_sensors__sensor_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sensors/{sensor_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sensor Stream */
        get: operations["get_sensor_stream_api_sensors__sensor_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plants */
        get: operations["get_plants_api_plants_get"];
        put?: never;
        /** Add Plant */
        post: operations["add_plant_api_plants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plants/{plant_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notes */
        get: operations["get_notes_api_plants__plant_id__notes_get"];
        put?: never;
        /** Post Note */
        post: operations["post_note_api_plants__plant_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
=======
        delete: operations["del_sensor_api_sensors_sensors__sensor_id__delete"];
        options?: never;
        head?: never;
        /** Update Sensor */
        patch: operations["update_sensor_api_sensors_sensors__sensor_id__patch"];
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
<<<<<<< HEAD
        /** NoteView */
        NoteView: {
            /** Id */
            id: number;
            /** Note */
            note: string;
            /** Rating */
            rating: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** PlantView */
        PlantView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** SensorView */
        SensorView: {
            /** Sensor Id */
            sensor_id: number;
            /** Plant Id */
            plant_id: number;
            /** Name */
            name: string;
        };
=======
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        /** UserSession */
        UserSession: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_get: {
        parameters: {
            query: {
                redirect: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cas_callback_api_auth_cas__redirect64__get: {
        parameters: {
            query: {
                ticket: string;
            };
            header?: never;
            path: {
                redirect64: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSession"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user_api_auth_delete_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
<<<<<<< HEAD
    get_user_sensors_api_sensors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
=======
    activate_sensor_api_sensors_sensors__sensor_id__session_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: number;
            };
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
<<<<<<< HEAD
                    "application/json": components["schemas"]["SensorView"][];
=======
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
                };
            };
        };
    };
<<<<<<< HEAD
    add_sensor_api_sensors_post: {
=======
    deactivate_sensor_api_sensors_sensors__sensor_id__session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_sensor_api_sensors_sensors_post: {
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        parameters: {
            query: {
                name: string;
                plant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
<<<<<<< HEAD
    activate_sensor_api_sensors__sensor_id__session_post: {
=======
    del_sensor_api_sensors_sensors__sensor_id__delete: {
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
<<<<<<< HEAD
    deactivate_sensor_api_sensors__sensor_id__session_delete: {
        parameters: {
            query?: never;
=======
    update_sensor_api_sensors_sensors__sensor_id__patch: {
        parameters: {
            query?: {
                plant_id?: number | null;
                name?: string | null;
            };
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
            header?: never;
            path: {
                sensor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
<<<<<<< HEAD
    del_sensor_api_sensors__sensor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensor_stream_api_sensors__sensor_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plants_api_plants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantView"][];
                };
            };
        };
    };
    add_plant_api_plants_post: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_plants__plant_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_note_api_plants__plant_id__notes_post: {
        parameters: {
            query: {
                note: string;
                rating: number;
            };
            header?: never;
            path: {
                plant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
=======
>>>>>>> 13e1dc504d87b0fa4288ec041312f01c468236f7
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
